import { Routes } from '@angular/router';
import { DashboardComponent } from './dashboard/dashboard.component';
import { SidebarComponent } from './sidebar/sidebar.component';
import { NavbarComponent } from './navbar/navbar.component';
import { PresenceComponent } from './presence/presence.component';
import { LoginComponent } from './login/login.component';
import { UtilisateurComponent } from './utilisateur/utilisateur.component';
import { DepartementComponent } from './departement/departement.component';
import { CohorteComponent } from './cohorte/cohorte.component';
import { HistoriqueComponent } from './historique/historique.component';
import { InscriptionComponent } from './inscription/inscription.component';
import { EditComponent } from './edit/edit.component';
import { AddDepartementComponent } from './add-departement/add-departement.component';
import { DashboardVigileComponent } from './dashboard-vigile/dashboard-vigile.component';
import { AddCohorteComponent } from './add-cohorte/add-cohorte.component';
import { EditCohorteComponent } from './edit-cohorte/edit-cohorte.component';
import { EmployeeListComponent } from './employee-list/employee-list.component';
import { ApprenantListCohorteComponent } from './apprenant-list-cohorte/apprenant-list-cohorte.component';
import { ForgotPasswordComponent } from './forgot-password/forgot-password.component';
import { ResetPasswordComponent } from './reset-password/reset-password.component';

export const routes: Routes = [
  { path: 'dashboard', component: DashboardComponent },
  { path: 'sidebar', component: SidebarComponent },
  { path: 'navbar', component: NavbarComponent },
  { path: 'presence', component: PresenceComponent },
  { path: 'login', component: LoginComponent },
  { path: 'utilisateur', component: UtilisateurComponent },
  { path: 'departement', component: DepartementComponent },
  { path: 'cohorte', component: CohorteComponent },
  { path: 'historique', component: HistoriqueComponent },
  { path: 'inscription', component: InscriptionComponent },
  { path: 'add-departement', component: AddDepartementComponent },
  { path: 'dashboard-vigile', component: DashboardVigileComponent },
  { path: 'add-cohorte', component: AddCohorteComponent },
  { path: 'edit/:id', component: EditComponent },
  { path: 'edit-cohorte/:id', component: EditCohorteComponent },
  { path: 'employee-list/:id', component: EmployeeListComponent },
  { path: 'departements/:departmentName/employees', component: EmployeeListComponent },
  { path: 'cohortes/:cohorteName/apprenants', component: ApprenantListCohorteComponent },
  { path: 'forgot-password', component: ForgotPasswordComponent },
  { path: 'reset-password', component: ResetPasswordComponent }
];
