# Utiliser une image Node.js pour le backend Arduino
FROM node:20

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY ./package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le reste du code
COPY . .

# Exposer le port sur lequel l'API fonctionne (exemple : 3000)
EXPOSE 3000

# Lancer l'application
CMD ["node", "server.js"]
